### ISSUE TITLE
Require populating Third Party API details in Log Table

### ISSUE THREAD

**Issue by SUDLifeShubhamMadhukar** [SudLife-Bank-N-Partner-Integration/PartnerIntegrationMicroServicesNew#2]
@SUDLifeRupali There is need to add three more tables in the Log table to storing Third Party API.
Kindly, connect for more reference.

**Comment by SUDLifeRupali** [comment]
for storing third party details new columns added.

**Comment by SUDLifeRupali** [comment]
completed on 03/07/2024
